# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

asyncMean <- function(data) {
    invisible(.Call('laterTest_asyncMean', PACKAGE = 'laterTest', data))
}

sayLater <- function(message, delay) {
    invisible(.Call('laterTest_sayLater', PACKAGE = 'laterTest', message, delay))
}

